const express=require('express')
const cors=require('cors')
const bodyParser=require('body-parser')
const userRoutes=require('./routes/user')
// const userRoutes=require('./routes')
const messageRoutes=require('./routes/message')
const groupRoutes=require('./routes/group')
const adminRoutes=require('./routes/admin')
const app=express()
const sequelize=require('./util/database')
const User=require('./models/user')
const Message=require('./models/message')
const Group=require('./models/group')
const userGroup=require('./models/usergroup')
app.use(cors())
app.use(bodyParser.json())
app.use(express.json())
app.use('/user',userRoutes)
app.use(groupRoutes)
app.use(messageRoutes)
app.use(adminRoutes)

User.belongsToMany(Group,{through:userGroup})
Group.belongsToMany(User,{through:userGroup})
User.hasMany(Message)
Message.belongsTo(User)

sequelize.sync()
.then(()=>{
    console.log('db is connected')
    app.listen(3200)
}).catch(err=>console.log(err))

